swagger: "2.0"
info:
  version: "0.0.1"
  title: Marketing JS (Mautic-SuiteCRM sync)
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /crm/lead:
    x-swagger-router-controller: crm_lead
    get:
      tags: ['SuiteCRM']
      description: Returns a list of leads.
      operationId: getLeads
      parameters:
        - name: max_results
          in: query
          description: the maximum number of leads to return, returns all leads if not specified.
          required: false
          type: number
          format: float
        - name: offset
          in: query
          description: the starting index in the leads array for pagination. defaults to 0 if not specified.
          required: false
          type: number
          format: float
        - name: order_by
          in: query
          description: the lead field to order the results by, defaults to date_entered if not specified.
          required: false
          type: string
        - name: order
          in: query
          description: the direction to order the results, enter 'ASC' for ascending or 'DESC' for descending, defaults to 'DESC'.
          type: string
          enum:
            - ASC
            - DESC
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Leads"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      tags: ["SuiteCRM"]
      description: Create Lead
      operationId: postLead
      parameters:
        - name: body
          in: body
          description: an array of 'name/value' objects.
          required: true
          schema:
            $ref: "#/definitions/NameValueList"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/LeadUpdate"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      tags: ["SuiteCRM"]
      description: Update an existing Lead.
      operationId: putLead
      parameters:
        - name: body
          in: body
          description: an array of 'name/value' objects, including the lead id.
          required: true
          schema:
            $ref: "#/definitions/NameValueList"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/LeadUpdate"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /crm/lead/{leadId}:
    x-swagger-router-controller: crm_lead
    delete:
      tags: ["SuiteCRM"]
      description: Deletes a Lead, rermoving it from the database permanetly.
      operationId: deleteLead
      parameters:
        - name: leadId
          in: path
          description: ID of the lead to delete
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Deleted"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      tags: ["SuiteCRM"]
      description: Returns a lead object matching the specified leadId.
      operationId: getLead
      parameters:
        - name: leadId
          in: path
          description: ID of the lead to fetch
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Lead"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /crm/lead/find-blanks:
    x-swagger-router-controller: crm_lead
    get:
      tags: ["SuiteCRM"]
      description: Returns a list of leads without contact details.
      operationId: getBlanks
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/LeadIds"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /crm/lead/find-by-email:
    x-swagger-router-controller: crm_lead
    post:
      tags: ["SuiteCRM"]
      description: Returns a list of matching leads.
      operationId: findByEmail
      parameters:
        - name: body
          in: body
          description: the email to search for.
          required: true
          schema:
            $ref: "#/definitions/Email"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Leads"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Acl:
    type: object
    required:
      - action
      - access
    properties:
      action:
        type: string
      access:
        type: boolean
  Deleted:
    type: object
  Email:
    type: object
    properties:
      email:
        type: string
        format: email
  FullName:
    type: object
    properties:
      fullName:
        type: string
  Hooks:
    type: object
  Lead:
    type: object
    required:
      - id
      - module_name
      - name_value_list
    properties:
      id:
        type: string
      module_name:
        type: string
      name_value_list:
        type: object
  Leads:
    type: object
    required:
      - leads
    properties:
      leads:
        type: array
        xml:
          name: "lead"
          wrapped: true
        items:
          $ref: "#/definitions/Lead"
  LeadId:
    type: string
  LeadIds:
    type: array
    xml:
      name: "blank lead ids"
      wrapped: true
    items:
      $ref: "#/definitions/LeadId"
  LeadUpdate:
    type: object
  Module:
    type: object
    required:
      - module_key
      - module_label
      - acls
    properties:
      module_key:
        type: string
      module_label:
        type: string
      favorites_enabled:
        type: boolean
      acls:
        type: array
        xml:
          name: "acls"
          wrapped: true
        items:
          $ref: "#/definitions/Acl"
  Modules:
    type: object
    required:
      - modules
    properties:
      modules:
        type: array
        xml:
          name: "module"
          wrapped: true
        items:
          $ref: "#/definitions/Module"
  NameValueList:
    type: array
    xml:
      name: "Name Value Pairs"
      wrapped: true
    items:
      $ref: "#/definitions/NameValuePair"
  NameValuePair:
    type: object
    required:
      - name
      - value
    properties:
      name:
        type: string
      value:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
